name: learn
on: [push]
#  push:
#    branches:
#      - main
#      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      #  - run: yarn install
      - run: cd web && node build-index.js
      # - run: node index.js
      - name: try to push a new file to the repo
        run: |
          # date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          if git commit -a -m "update generated"; then echo 0; fi
          git push
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web # The folder the action should deploy.
